services:
  postgres:
    image: postgres:17
    container_name: avia_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: avia
      POSTGRES_PASSWORD: avia
      POSTGRES_DB: demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U avia -d postgres']
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
